version: '3.8'

services:
  pos-sdk:
    image: couponbureau/pos-sdk:latest
    container_name: pos-sdk
    restart: always
    depends_on:
      - redis
      - squid_proxy
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HTTP_PROXY=http://squid_proxy:3128
      - HTTPS_PROXY=http://squid_proxy:3128
      - NO_PROXY=localhost,127.0.0.1,*.thecouponbureau.org,api.try.thecouponbureau.org,api.portal.thecouponbureau.org,host.docker.internal
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6372:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

  squid_proxy:
    image: sameersbn/squid:latest
    container_name: squid_proxy
    restart: always
    ports:
      - "3128:3128"  # Expose Squid proxy
    networks:
      - app_network
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro  # Mount custom Squid config

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
